export const servicesPart2 = [
    // PART 2: Pujas 25-48
    {
        name: 'Ram Raksha Stotra',
        name_hi: 'राम रक्षा स्तोत्र',
        category: 'Path & Stotra',
        base_price: 1500,
        duration: '1 Hour',
        pandits_required: 1,
        description: 'Powerful protective hymn of Lord Ram for shielding from all dangers and negative energies.',
        description_hi: 'सभी खतरों और नकारात्मक ऊर्जाओं से सुरक्षा हेतु भगवान राम का शक्तिशाली रक्षा स्तोत्र।',
        items_included: ['Vedic Pandit', 'Ram Raksha Stotra Book', 'Flowers & Incense'],
        samagri_available: false,
        benefits: ['Protection', 'Courage', 'Negative energy removal', 'Ram blessings']
    },
    {
        name: 'Ramayan Paath',
        name_hi: 'रामायण पाठ',
        category: 'Path & Stotra',
        base_price: 5100,
        duration: '1-3 Days',
        pandits_required: 2,
        description: 'Complete or Akhand recitation of Ramcharitmanas for familial harmony, righteousness, and divine grace.',
        description_hi: 'पारिवारिक सामंजस्य, धर्म और दिव्य कृपा हेतु रामचरितमानस का सम्पूर्ण या अखंड पाठ।',
        items_included: ['2 Vedic Pandits', 'Ramcharitmanas', 'Akhand Jyoti', 'Havan Samagri', 'Prasad & Bhandara'],
        benefits: ['Family harmony', 'Righteousness', 'Divine grace', 'Peace & prosperity']
    },
    {
        name: 'Rudrabhishek',
        name_hi: 'रुद्राभिषेक',
        category: 'Special Puja',
        base_price: 4100,
        duration: '2-3 Hours',
        pandits_required: 1,
        description: 'Sacred abhishek of Lord Shiva with milk, honey, curd, and holy offerings for blessings of health and prosperity.',
        description_hi: 'स्वास्थ्य और समृद्धि के आशीर्वाद हेतु दूध, शहद, दही और पवित्र सामग्री से भगवान शिव का अभिषेक।',
        items_included: ['Vedic Pandit', 'Shivling', 'Panchamrit (Milk, Honey, Curd, Ghee, Sugar)', 'Bilva Patra', 'Havan Samagri'],
        benefits: ['Health & prosperity', 'Sin removal', 'Wish fulfillment', 'Shiva blessings']
    },
    {
        name: 'Vivah (Marriage Ceremony)',
        name_hi: 'विवाह',
        category: 'Sanskar',
        base_price: 11000,
        duration: '4-6 Hours',
        pandits_required: 2,
        description: 'Complete Vedic marriage ceremony with all traditional rituals, mantras, and sacred fire.',
        description_hi: 'सम्पूर्ण वैदिक विवाह संस्कार — सभी पारंपरिक रीति-रिवाज, मन्त्र और पवित्र अग्नि के साथ।',
        items_included: ['2 Experienced Pandits', 'Mandap Setup Guidance', 'Havan Kund & Samagri', 'All Vivah Rituals', 'Ganesh & Kalash Sthapana'],
        benefits: ['Auspicious union', 'Lifelong bond', 'Family blessings', 'Vedic tradition']
    },
    {
        name: 'Haldi Kalash',
        name_hi: 'हल्दी कलश',
        category: 'Sanskar',
        base_price: 2100,
        duration: '1-2 Hours',
        pandits_required: 1,
        description: 'Pre-wedding Haldi ceremony with Vedic rituals and traditional kalash sthapana.',
        description_hi: 'वैदिक विधि और पारंपरिक कलश स्थापना के साथ विवाह पूर्व हल्दी संस्कार।',
        items_included: ['Vedic Pandit', 'Haldi & Kalash', 'Mango Leaves', 'Coconut & Flowers'],
        benefits: ['Purification', 'Beauty blessings', 'Auspicious beginning', 'Traditional blessing']
    },
    {
        name: 'Surya Puja',
        name_hi: 'सूर्य पूजा',
        category: 'Graha Puja',
        base_price: 2500,
        duration: '2 Hours',
        pandits_required: 1,
        description: 'Sun worship for vitality, leadership, government favors, and relief from Surya-related doshas.',
        description_hi: 'जीवन शक्ति, नेतृत्व, सरकारी कार्यों में सफलता और सूर्य दोष निवारण हेतु सूर्य पूजा।',
        items_included: ['Vedic Pandit', 'Red Flowers & Wheat', 'Surya Yantra', 'Havan Samagri'],
        benefits: ['Vitality & health', 'Leadership qualities', 'Government success', 'Surya blessings']
    },
    {
        name: 'Kali Puja',
        name_hi: 'काली पूजा',
        category: 'Special Puja',
        base_price: 5100,
        duration: '3-4 Hours',
        pandits_required: 1,
        description: 'Worship of Goddess Kali for destruction of evil forces, protection, and immense power.',
        description_hi: 'बुरी शक्तियों के विनाश, सुरक्षा और अपार शक्ति हेतु माँ काली की पूजा।',
        items_included: ['Experienced Tantrik Pandit', 'Kali Murti/Yantra', 'Red Flowers & Hibiscus', 'Havan Samagri', 'Special Offerings'],
        benefits: ['Evil force destruction', 'Immense protection', 'Fearlessness', 'Kali Mata blessings']
    },
    {
        name: 'Krishna Janmashtami Puja',
        name_hi: 'कृष्ण जन्माष्टमी पूजा',
        category: 'Special Puja',
        base_price: 3100,
        duration: '3-4 Hours',
        pandits_required: 1,
        description: 'Celebration of Lord Krishna birth with midnight puja, bhajan, and traditional rituals.',
        description_hi: 'भगवान कृष्ण के जन्मोत्सव — मध्यरात्रि पूजा, भजन और पारंपरिक अनुष्ठानों के साथ।',
        items_included: ['Vedic Pandit', 'Krishna Murti & Jhula', 'Makhan & Mishri', 'Flowers & Tulsi', 'Prasad'],
        benefits: ['Krishna blessings', 'Family happiness', 'Prosperity', 'Spiritual growth']
    },
    {
        name: 'Narayan Bali Shraddh',
        name_hi: 'नारायण बली श्राद्ध',
        category: 'Shraddh & Pitra',
        base_price: 11000,
        duration: '1 Day',
        pandits_required: 2,
        description: 'Advanced ancestral rites to liberate souls of departed from cycle of rebirth and relieve Pitra dosh.',
        description_hi: 'पूर्वजों की आत्माओं की मुक्ति और पितृ दोष निवारण हेतु उन्नत श्राद्ध कर्म।',
        items_included: ['2 Experienced Pandits', 'Bali Vidhi Samagri', 'Pind Daan Items', 'Havan & Tarpan', 'Brahmin Bhoj'],
        benefits: ['Ancestral soul liberation', 'Pitra dosh remedy', 'Family peace', 'Spiritual merit']
    },
    {
        name: 'Satyanarayan Katha',
        name_hi: 'सत्यानारायण कथा',
        category: 'Special Puja',
        base_price: 2100,
        duration: '2-3 Hours',
        pandits_required: 1,
        description: 'Most popular puja for prosperity and well-being, performed on Purnima or auspicious occasions.',
        description_hi: 'समृद्धि और कल्याण हेतु सबसे लोकप्रिय पूजा — पूर्णिमा या शुभ अवसरों पर की जाती है।',
        items_included: ['Vedic Pandit', 'Satyanarayan Katha Book', 'Panchamrit & Prasad', 'Banana Leaves', 'Havan Samagri'],
        benefits: ['Wish fulfillment', 'Prosperity', 'Family well-being', 'Vishnu blessings']
    },
    {
        name: 'Chhaya Daan',
        name_hi: 'छाया दान',
        category: 'Daan & Charity',
        base_price: 2100,
        duration: '1 Hour',
        pandits_required: 1,
        description: 'Shadow donation ritual to ward off malefic planetary effects and earn spiritual merit.',
        description_hi: 'ग्रहों के अशुभ प्रभावों को दूर करने और आध्यात्मिक पुण्य अर्जित करने हेतु छाया दान।',
        items_included: ['Vedic Pandit', 'Shadow Daan Items', 'Mantra Chanting'],
        samagri_available: false,
        benefits: ['Planetary pacification', 'Spiritual merit', 'Health benefits', 'Dosh nivaran']
    },
    {
        name: 'Grahan Dosh Nivaran Puja',
        name_hi: 'ग्रहण दोष निवारण पूजा',
        category: 'Dosh Nivaran',
        base_price: 5100,
        duration: '3-4 Hours',
        pandits_required: 1,
        description: 'Specific puja to remove the ill effects of being born during an eclipse or grahan dosh in kundli.',
        description_hi: 'ग्रहण के समय जन्म या कुंडली में ग्रहण दोष के दुष्प्रभावों को दूर करने हेतु विशेष पूजा।',
        items_included: ['Experienced Vedic Pandit', 'Grahan Dosh Yantra', 'Havan Samagri', 'Daan Items'],
        benefits: ['Eclipse dosh removal', 'Health improvement', 'Positive energy', 'Peace of mind']
    },
    {
        name: 'Karj Mukti Puja',
        name_hi: 'कर्ज मुक्ति पूजा',
        category: 'Dosh Nivaran',
        base_price: 3500,
        duration: '2-3 Hours',
        pandits_required: 1,
        description: 'Special puja to overcome debt and financial burdens through divine intervention.',
        description_hi: 'दिव्य हस्तक्षेप द्वारा ऋण और आर्थिक बोझ से मुक्ति हेतु विशेष पूजा।',
        items_included: ['Vedic Pandit', 'Lakshmi & Ganesh Puja', 'Havan Samagri', 'Specific Daan'],
        benefits: ['Debt freedom', 'Financial stability', 'Prosperity', 'Mental peace']
    },
    {
        name: 'Rog Mukti Puja',
        name_hi: 'रोग मुक्ति पूजा',
        category: 'Dosh Nivaran',
        base_price: 3500,
        duration: '2-3 Hours',
        pandits_required: 1,
        description: 'Healing puja for relief from chronic diseases and health issues through Vedic rituals and mantras.',
        description_hi: 'वैदिक अनुष्ठानों और मन्त्रों द्वारा पुरानी बीमारियों और स्वास्थ्य समस्याओं से राहत हेतु उपचार पूजा।',
        items_included: ['Vedic Pandit', 'Mrityunjaya Jaap', 'Dhanvantari Puja', 'Havan Samagri', 'Aushadhi Daan'],
        benefits: ['Disease relief', 'Health restoration', 'Longevity', 'Divine healing']
    },
    {
        name: 'Ghritdhari',
        name_hi: 'घृतधारी',
        category: 'Special Puja',
        base_price: 2100,
        duration: '1-2 Hours',
        pandits_required: 1,
        description: 'Continuous pouring of ghee on Shivling for wish fulfillment and Shiva blessings.',
        description_hi: 'मनोकामना पूर्ति और शिव आशीर्वाद हेतु शिवलिंग पर घी की अविरल धारा।',
        items_included: ['Vedic Pandit', 'Pure Cow Ghee', 'Shivling', 'Bilva Patra & Flowers'],
        benefits: ['Wish fulfillment', 'Sin removal', 'Prosperity', 'Shiva blessings']
    },
    {
        name: 'Mandap Achchhadan',
        name_hi: 'मंडप आच्छादन',
        category: 'Sanskar',
        base_price: 3100,
        duration: '2-3 Hours',
        pandits_required: 1,
        description: 'Traditional ritual of decorating and consecrating the wedding mandap before the ceremony.',
        description_hi: 'विवाह संस्कार से पूर्व मंडप को सजाने और पवित्र करने की पारंपरिक विधि।',
        items_included: ['Vedic Pandit', 'Mandap Decoration Items', 'Kalash & Nariyal', 'Mango Leaves'],
        benefits: ['Auspicious ceremony', 'Divine blessings', 'Traditional beauty', 'Sacred space']
    },
    {
        name: 'Kal Bhairav Puja',
        name_hi: 'काल भैरव पूजा',
        category: 'Special Puja',
        base_price: 5100,
        duration: '3-4 Hours',
        pandits_required: 1,
        description: 'Worship of Kal Bhairav, fierce form of Shiva, for protection from enemies and black magic.',
        description_hi: 'शत्रुओं और काले जादू से रक्षा हेतु शिव के उग्र रूप काल भैरव की पूजा।',
        items_included: ['Experienced Tantrik Pandit', 'Bhairav Yantra', 'Mustard Oil & Black Items', 'Havan Samagri'],
        benefits: ['Enemy protection', 'Black magic removal', 'Fearlessness', 'Bhairav blessings']
    },
    {
        name: 'Tripindi Shraddh',
        name_hi: 'त्रिपिंडी श्राद्ध',
        category: 'Shraddh & Pitra',
        base_price: 5100,
        duration: '3-4 Hours',
        pandits_required: 1,
        description: 'Special ancestral rites for three generations of departed souls to attain peace and liberation.',
        description_hi: 'तीन पीढ़ियों की दिवंगत आत्माओं की शांति और मुक्ति हेतु विशेष श्राद्ध कर्म।',
        items_included: ['Experienced Vedic Pandit', 'Tripindi Samagri', 'Pind Daan Items', 'Tarpan & Havan', 'Brahmin Bhoj'],
        benefits: ['3-generation ancestral peace', 'Pitra dosh removal', 'Family prosperity', 'Spiritual merit']
    },
    {
        name: 'Kal Sarp Dosh Nivaran Puja',
        name_hi: 'काल सर्प दोष निवारण पूजा',
        category: 'Dosh Nivaran',
        base_price: 7500,
        duration: '4-5 Hours',
        pandits_required: 2,
        description: 'Powerful remedy puja for Kal Sarp Yog/Dosh in kundli — removes obstacles in career, marriage, and health.',
        description_hi: 'कुंडली में काल सर्प योग/दोष का शक्तिशाली निवारण — करियर, विवाह और स्वास्थ्य में बाधाओं को दूर करता है।',
        items_included: ['2 Experienced Pandits', 'Nag Puja & Yantra', 'Silver Nag', 'Havan Samagri', 'Specific Daan'],
        benefits: ['All-round obstacle removal', 'Career growth', 'Marriage facilitation', 'Health improvement']
    },
    {
        name: 'Manglik Dosh Nivaran Puja',
        name_hi: 'मांगलिक दोष निवारण पूजा',
        category: 'Dosh Nivaran',
        base_price: 5100,
        duration: '3-4 Hours',
        pandits_required: 1,
        description: 'Essential puja for Manglik individuals to reduce Mars affliction and enable smooth marriage.',
        description_hi: 'मांगलिक व्यक्तियों के लिए मंगल दोष को कम करने और सुचारू विवाह हेतु आवश्यक पूजा।',
        items_included: ['Experienced Vedic Pandit', 'Mangal Yantra', 'Red Coral & Items', 'Kumbh Vivah Items', 'Havan Samagri'],
        benefits: ['Mangal dosh remedy', 'Marriage facilitation', 'Marital harmony', 'Confidence']
    },
    {
        name: 'Pitra Dosh Nivaran Puja',
        name_hi: 'पितृ दोष निवारण पूजा',
        category: 'Dosh Nivaran',
        base_price: 5100,
        duration: '3-4 Hours',
        pandits_required: 1,
        description: 'Comprehensive puja to pacify displeased ancestors and remove Pitra dosh effects from kundli.',
        description_hi: 'कुंडली से पितृ दोष के प्रभावों को दूर करने और अप्रसन्न पूर्वजों को शांत करने हेतु व्यापक पूजा।',
        items_included: ['Experienced Vedic Pandit', 'Tarpan Samagri', 'Pind Daan Items', 'Havan & Homam', 'Brahmin Bhoj'],
        benefits: ['Ancestral peace', 'Dosh removal', 'Family harmony', 'Progeny blessings']
    },
    {
        name: 'Geeta Paath',
        name_hi: 'गीता पाठ',
        category: 'Path & Stotra',
        base_price: 2100,
        duration: '3-4 Hours',
        pandits_required: 1,
        description: 'Complete recitation of Shrimad Bhagavad Gita for spiritual wisdom and life guidance.',
        description_hi: 'आध्यात्मिक ज्ञान और जीवन मार्गदर्शन हेतु श्रीमद भगवद गीता का सम्पूर्ण पाठ।',
        items_included: ['Vedic Pandit', 'Bhagavad Gita', 'Flowers & Incense', 'Prasad'],
        samagri_available: false,
        benefits: ['Spiritual wisdom', 'Life clarity', 'Peace of mind', 'Krishna blessings']
    },
    {
        name: 'Gaya Shraddh',
        name_hi: 'गया श्राद्ध',
        category: 'Shraddh & Pitra',
        base_price: 11000,
        duration: '1 Day',
        pandits_required: 1,
        description: 'Sacred Pind Daan at Gaya for liberation of ancestral souls — performed by pandit with Gaya vidhi expertise.',
        description_hi: 'पूर्वजों की आत्माओं की मुक्ति हेतु गया में पवित्र पिंड दान — गया विधि विशेषज्ञ पंडित द्वारा।',
        items_included: ['Gaya Vidhi Expert Pandit', 'Pind Daan Samagri', 'Tarpan Items', 'Brahmin Bhoj', 'Travel Guidance'],
        benefits: ['Ultimate ancestral liberation', 'Moksha for departed', 'Pitra dosh cure', 'Spiritual merit']
    },
    {
        name: 'Annaprashan',
        name_hi: 'अन्नप्राशन',
        category: 'Sanskar',
        base_price: 2100,
        duration: '1-2 Hours',
        pandits_required: 1,
        description: 'Baby first rice-feeding ceremony with Vedic mantras for health, growth, and prosperity of the child.',
        description_hi: 'शिशु के स्वास्थ्य, विकास और समृद्धि हेतु वैदिक मन्त्रों के साथ प्रथम अन्न ग्रहण संस्कार।',
        items_included: ['Vedic Pandit', 'Silver Bowl & Spoon', 'Kheer/Payasam', 'Ganesh Puja', 'Havan Samagri'],
        benefits: ['Child health', 'Growth & prosperity', 'Digestive strength', 'Auspicious beginning']
    }
];
