export const servicesPart3 = [
    // PART 3: Pujas 49-72
    {
        name: 'Shraddh',
        name_hi: 'श्राद्ध',
        category: 'Shraddh & Pitra',
        base_price: 2500,
        duration: '1 Hour',
        pandits_required: 1,
        description: 'Annual ancestral rites performed during Pitru Paksha to honor departed souls.',
        description_hi: 'पितृ पक्ष के दौरान दिवंगत पूर्वजों के सम्मान में किया जाने वाला वार्षिक श्राद्ध कर्म।',
        items_included: ['Vedic Pandit', 'Pind Daan Samagri', 'Kush & Tit (Sesame)', 'Tarpan Water', 'Dakshina'],
        benefits: ['Ancestral blessings', 'Family continuity', 'Peace & harmony', 'Good karma']
    },
    {
        name: 'Katha (General)',
        name_hi: 'कथा',
        category: 'Special Puja',
        base_price: 1500,
        duration: '1-2 Hours',
        pandits_required: 1,
        description: 'General narrative worship of gods/goddesses for specific occasions and blessings.',
        description_hi: 'विशेष अवसरों और आशीर्वाद हेतु देवी-देवताओं की सामान्य कथा।',
        items_included: ['Vedic Pandit', 'Katha Book', 'Flowers & Prasad', 'Lamp & Incense'],
        benefits: ['Divine stories', 'Moral guidance', 'Spiritual atmosphere', 'Blessings']
    },
    {
        name: 'Teej Vrat Katha',
        name_hi: 'तीज व्रत कथा',
        category: 'Special Puja',
        base_price: 1500,
        duration: '1 Hour',
        pandits_required: 1,
        description: 'Traditional story recitation for women observing Teej fast for husband longevity.',
        description_hi: 'पति की दीर्घायु हेतु तीज व्रत रखने वाली महिलाओं के लिए पारंपरिक कथा पाठ।',
        items_included: ['Vedic Pandit', 'Teej Katha Book', 'Fruits & Sweets', 'Makeup Items (Suhag)'],
        benefits: ['Marital bliss', 'Husband longevity', 'Family happiness', 'Tradition']
    },
    {
        name: 'Jivitputrika Vrat Katha',
        name_hi: 'जीवित पुत्रिका व्रत कथा',
        category: 'Special Puja',
        base_price: 1500,
        duration: '1 Hour',
        pandits_required: 1,
        description: 'Sacred story for mothers fasting for the well-being and long life of their children.',
        description_hi: 'संतान के कल्याण और दीर्घायु हेतु माताओं द्वारा किए जाने वाले व्रत की पवित्र कथा।',
        items_included: ['Vedic Pandit', 'Jivitputrika Katha Book', 'Fruits & Thread (Jitiya)'],
        benefits: ['Child safety', 'Longevity', 'Health & success', 'Motherly blessings']
    },
    {
        name: 'Ekadashi Vrat Katha',
        name_hi: 'एकादशी व्रत कथा',
        category: 'Special Puja',
        base_price: 1500,
        duration: '1 Hour',
        pandits_required: 1,
        description: 'Bi-monthly story recitation on Ekadashi for Vishnu blessings and spiritual merit.',
        description_hi: 'विष्णु आशीर्वाद और आध्यात्मिक पुण्य हेतु एकादशी पर पाक्षिक कथा पाठ।',
        items_included: ['Vedic Pandit', 'Ekadashi Mahatmya Book', 'Tulsi & Flowers', 'Fruits'],
        benefits: ['Sin removal', 'Moksha path', 'Vishnu grace', 'Spiritual purity']
    },
    {
        name: 'Chauth Vrat Katha',
        name_hi: 'चौथ व्रत कथा',
        category: 'Special Puja',
        base_price: 1500,
        duration: '1 Hour',
        pandits_required: 1,
        description: 'Story of Sankashti/Karwa Chauth for overcoming obstacles and husband well-being.',
        description_hi: 'बाधा निवारण और पति के कल्याण हेतु संकष्टी/करवा चौथ की कथा।',
        items_included: ['Vedic Pandit', 'Chauth Katha Book', 'Arghya Samagri', 'Modak/Sweets'],
        benefits: ['Obstacle removal', 'Marital happiness', 'Ganesh blessings', 'Moon worship']
    },
    {
        name: 'Anant Puja',
        name_hi: 'अनंत पूजा',
        category: 'Special Puja',
        base_price: 2100,
        duration: '2 Hours',
        pandits_required: 1,
        description: 'Worship of Lord Anant (Vishnu) with sacred thread for endless prosperity and vow fulfillment.',
        description_hi: 'अनंत समृद्धि और व्रत पूर्ति हेतु पवित्र धागे के साथ भगवान अनंत (विष्णु) की पूजा।',
        items_included: ['Vedic Pandit', 'Anant Sutra (Thread)', 'Vishnu Idol', 'Sheshnag Puja', 'Sweets'],
        benefits: ['Endless prosperity', 'Vow fulfillment', 'Protection', 'Vishnu blessings']
    },
    {
        name: 'Vishwakarma Puja',
        name_hi: 'विश्वकर्मा पूजा',
        category: 'Home & Business',
        base_price: 3100,
        duration: '2 Hours',
        pandits_required: 1,
        description: 'Worship of the divine architect for success in engineering, construction, and craftsmanship.',
        description_hi: 'इंजीनियरिंग, निर्माण और शिल्प कौशल में सफलता हेतु दिव्य वास्तुकार की पूजा।',
        items_included: ['Vedic Pandit', 'Vishwakarma Idol/Photo', 'Tools Puja', 'Vehicle Puja', 'Sweets'],
        benefits: ['Technical success', 'Safety with tools', 'Innovation', 'Craftsmanship blessings']
    },
    {
        name: 'Kanakdhara Stotra',
        name_hi: 'कनक धारा स्तोत्र',
        category: 'Path & Stotra',
        base_price: 1500,
        duration: '1 Hour',
        pandits_required: 1,
        description: 'Powerful hymn by Adi Shankaracharya dedicated to Goddess Lakshmi for immense wealth.',
        description_hi: 'अपार धन प्राप्ति हेतु आदि शंकराचार्य द्वारा रचित माँ लक्ष्मी का शक्तिशाली स्तोत्र।',
        items_included: ['Vedic Pandit', 'Kanakdhara Stotra Book', 'Lotus Flowers', 'Gold Coin/Item'],
        samagri_available: false,
        benefits: ['Wealth accumulation', 'Poverty removal', 'Financial luck', 'Lakshmi grace']
    },
    {
        name: 'Lakshmi Puja',
        name_hi: 'लक्ष्मी पूजा',
        category: 'Special Puja',
        base_price: 2500,
        duration: '1.5 Hours',
        pandits_required: 1,
        description: 'General worship of Goddess Lakshmi for wealth, fortune, and prosperity.',
        description_hi: 'धन, भाग्य और समृद्धि हेतु माँ लक्ष्मी की सामान्य पूजा।',
        items_included: ['Vedic Pandit', 'Lakshmi Idol', 'Lotus Flowers', 'Sweets & Fruits', 'Coins'],
        benefits: ['Wealth & fortune', 'Business growth', 'Household prosperity', 'Divine grace']
    },
    {
        name: 'Saraswati Puja',
        name_hi: 'सरस्वती पूजा',
        category: 'Special Puja',
        base_price: 2500,
        duration: '1.5 Hours',
        pandits_required: 1,
        description: 'Worship of Goddess of Knowledge for wisdom, arts, music, and academic success.',
        description_hi: 'ज्ञान, कला, संगीत और शैक्षणिक सफलता हेतु विद्या की देवी की पूजा।',
        items_included: ['Vedic Pandit', 'Saraswati Idol', 'Books & Pens', 'White Flowers', 'Yellow Sweets'],
        benefits: ['Academic success', 'Artistic skills', 'Wisdom & memory', 'Saraswati blessings']
    },
    {
        name: 'Akhand Puja',
        name_hi: 'अखंड पूजा',
        category: 'Special Puja',
        base_price: 11000,
        duration: '24 Hours',
        pandits_required: 3,
        description: 'Continuous worship (usually Ramayan/Kirtan) without interruption for deep spiritual impact.',
        description_hi: 'गहरे आध्यात्मिक प्रभाव हेतु बिना किसी रुकावट के निरंतर पूजा (सामान्यतः रामायण/कीर्तन)।',
        items_included: ['Team of Pandits (Shift-wise)', 'Akhand Jyoti', 'Sound System (if needed)', 'Havan Samagri', 'Continuous Prasad'],
        benefits: ['Deep spiritual vibration', 'Community blessing', 'Divine atmosphere', 'Miraculous results']
    },
    {
        name: 'Ganesh Puja',
        name_hi: 'गणेश पूजा',
        category: 'Special Puja',
        base_price: 2100,
        duration: '1 Hour',
        pandits_required: 1,
        description: 'Detailed worship of Lord Ganesh to remove obstacles before any new venture.',
        description_hi: 'किसी भी नए कार्य से पूर्व बाधाओं को दूर करने हेतु भगवान गणेश की विस्तृत पूजा।',
        items_included: ['Vedic Pandit', 'Ganesh Idol', 'Durva Grass', 'Modak', 'Red Flowers'],
        benefits: ['Obstacle removal', 'Wisdom & intellect', 'New beginnings', 'Riddhi-Siddhi']
    },
    {
        name: 'Vishnu Abhishek',
        name_hi: 'विष्णु अभिषेक',
        category: 'Special Puja',
        base_price: 3500,
        duration: '2 Hours',
        pandits_required: 1,
        description: 'Ceremonial bathing of Lord Vishnu idol with sacred substances for preservation and protection.',
        description_hi: 'संरक्षण और सुरक्षा हेतु पवित्र पदार्थों से भगवान विष्णु की मूर्ति का औपचारिक अभिषेक।',
        items_included: ['Vedic Pandit', 'Vishnu/Shaligram Idol', 'Panchamrit', 'Tulsi Leaves', 'Conch Shell'],
        benefits: ['Forgiveness of sins', 'Protection', 'Prosperity', 'Vishnu grace']
    },
    {
        name: 'Shrimad Bhagwat Mahapuran Katha (Saptah)',
        name_hi: 'श्रीमद भागवत महापुराण कथा (साप्ताहिक)',
        category: 'Path & Stotra',
        base_price: 25000,
        duration: '7 Days',
        pandits_required: 1,
        description: '7-day recitation of Bhagwat Puran covering the life and teachings of Lord Krishna.',
        description_hi: 'भगवान कृष्ण के जीवन और शिक्षाओं को कवर करने वाली भागवत पुराण की 7-दिवसीय कथा।',
        items_included: ['Expert Katha Vyas', 'Musical Accompaniment (Optional)', 'Vyas Gaddi Setup', 'Daily Prasad', 'Final Bhandara'],
        benefits: ['Ultimate moksha', 'Divine knowledge', 'Krishna bhakti', 'Family liberation']
    },
    {
        name: 'Bhumi Daan',
        name_hi: 'भूमि दान',
        category: 'Daan & Charity',
        base_price: 5100,
        duration: '2 Hours',
        pandits_required: 1,
        description: 'Symbolic or actual donation of land for temples/ashrams to earn eternal merit.',
        description_hi: 'मंदिरों/आश्रमों के लिए भूमि का प्रतीकात्मक या वास्तविक दान — अनंत पुण्य प्राप्ति हेतु।',
        items_included: ['Vedic Pandit', 'Sankalp Vidhi', 'Soil from Land', 'Documents (Symbolic)', 'Dakshina'],
        benefits: ['Eternal merit', 'Stability', 'Legacy', 'Earth blessings']
    },
    {
        name: 'Swarn Daan',
        name_hi: 'स्वर्ण दान',
        category: 'Daan & Charity',
        base_price: 2100,
        duration: '1 Hour',
        pandits_required: 1,
        description: 'Donation of gold to Brahmins or temples for wealth and solar blessings.',
        description_hi: 'धन और सूर्य आशीर्वाद हेतु ब्राह्मणों या मंदिरों को स्वर्ण दान।',
        samagri_available: false,
        items_included: ['Vedic Pandit', 'Sankalp Vidhi', 'Gold Item (client provides)', 'Dakshina'],
        benefits: ['Immense wealth', 'Solar grace', 'High status', 'Purity']
    },
    {
        name: 'Gau Daan',
        name_hi: 'गाय दान',
        category: 'Daan & Charity',
        base_price: 5100,
        duration: '1 Hour',
        pandits_required: 1,
        description: 'Donation of a cow (or equivalent value) considered the highest form of charity in Vedas.',
        description_hi: 'वेदों में दान का सर्वोच्च रूप माना जाने वाला गाय (या समतुल्य मूल्य) का दान।',
        items_included: ['Vedic Pandit', 'Cow (Symbolic/Real)', 'Fodder', 'Rope & Bucket', 'Sankalp'],
        benefits: ['Highest merit (Punya)', 'Moksha', 'Sin liberation', 'Vaitarni crossing']
    },
    {
        name: 'Chitragupta Puja',
        name_hi: 'चित्रगुप्त पूजा',
        category: 'Special Puja',
        base_price: 2500,
        duration: '1-2 Hours',
        pandits_required: 1,
        description: 'Worship of the divine record-keeper by Kayastha community for justice and account-keeping.',
        description_hi: 'न्याय और लेखा-जोखा हेतु कायस्थ समुदाय द्वारा दिव्य चित्रगुप्त जी की पूजा।',
        items_included: ['Vedic Pandit', 'Chitragupta Photo', 'Pen & Ink Pot', 'Accounts Book', 'Sweets'],
        benefits: ['Justice', 'Written word success', 'Career stability', 'Divine record grace']
    },
    {
        name: 'Govardhan Puja',
        name_hi: 'गोवर्धन पूजा',
        category: 'Special Puja',
        base_price: 3100,
        duration: '2 Hours',
        pandits_required: 1,
        description: 'Worship of Govardhan Hill and cows, usually performed the day after Diwali.',
        description_hi: 'दिवाली के अगले दिन की जाने वाली गोवर्धन पर्वत और गायों की पूजा।',
        items_included: ['Vedic Pandit', 'Cow Dung Hill (Symbolic)', 'Annakut (Food Mountain)', 'Flowers', 'Incense'],
        benefits: ['Nature blessings', 'Protection from calamities', 'Prosperity', 'Krishna grace']
    },
    {
        name: 'Chhath Puja',
        name_hi: 'छठ पूजा',
        category: 'Special Puja',
        base_price: 5100,
        duration: '2 Days',
        pandits_required: 1,
        description: 'Major sun-worship festival for health, prosperity, and offspring, widely celebrated in Bihar/UP.',
        description_hi: 'बिहार/यूपी में व्यापक रूप से मनाया जाने वाला सूर्य-पूजा का महापर्व — स्वास्थ्य, समृद्धि और संतान हेतु।',
        items_included: ['Vedic Pandit', 'Soop & Dala', 'Seasonal Fruits', 'Thekua', 'Arghya Items'],
        benefits: ['Vitality', 'Cure from diseases', 'Offspring well-being', 'Solar energy']
    },
    {
        name: 'Garud Puran Paath',
        name_hi: 'गरुड़ पुराण पाठ',
        category: 'Path & Stotra',
        base_price: 5100,
        duration: '10 Days',
        pandits_required: 1,
        description: 'Recitation of Garud Puran after death to guide the soul through the afterlife journey.',
        description_hi: 'मृत्यु के पश्चात आत्मा को परलोक यात्रा में मार्गदर्शन हेतु गरुड़ पुराण का पाठ।',
        items_included: ['Vedic Pandit', 'Garud Puran Book', 'Daily Lamp', 'Flowers', 'Final Shanti'],
        samagri_available: false,
        benefits: ['Soul guidance', 'Peace for departed', 'Understanding afterlife', 'Moksha']
    },
    {
        name: 'Harivansh Puran Paath',
        name_hi: 'हरिवंश पुराण पाठ',
        category: 'Path & Stotra',
        base_price: 7500,
        duration: '7 Days',
        pandits_required: 1,
        description: 'Recitation of Harivansh Puran for progeny (santān prapti) and family lineage continuity.',
        description_hi: 'संतान प्राप्ति और वंश निरंतरता हेतु हरिवंश पुराण का पाठ।',
        items_included: ['Vedic Pandit', 'Harivansh Puran Book', 'Krishna Idol', 'Tulsi', 'Prasad'],
        benefits: ['Progeny (Child birth)', 'Lineage continuity', 'Krishna blessings', 'Family joy']
    },
    {
        name: 'Amla Puja & Gupt Daan',
        name_hi: 'आवाला पूजा एवं गुप्त दान',
        category: 'Special Puja',
        base_price: 2100,
        duration: '1-2 Hours',
        pandits_required: 1,
        description: 'Worship of Amla tree (Vishnu form) and secret charity for multiplied spiritual merit.',
        description_hi: 'आंवला वृक्ष (विष्णु रूप) की पूजा और गुणित आध्यात्मिक पुण्य हेतु गुप्त दान।',
        items_included: ['Vedic Pandit', 'Amla Tree/Branch', 'Milk & Water', 'Deep Daan', 'Secret Donation Items'],
        benefits: ['Multiplied merit', 'Vishnu grace', 'Health (Vitamin C)', 'Sin removal']
    }
];
