export const servicesPart1 = [
    // MANTRA JAAP
    {
        name: 'Rahu Vedic Mantra Jaap',
        name_hi: 'राहु वैदिक मन्त्र जाप',
        category: 'Mantra Jaap',
        base_price: 5100,
        duration: '2-3 Hours',
        mantra_count: '18,000',
        pandits_required: 1,
        description: 'Powerful Vedic mantra jaap to pacify Rahu and reduce its malefic effects on career, health, and relationships.',
        description_hi: 'राहु ग्रह की शांति के लिए वैदिक मन्त्र जाप। करियर, स्वास्थ्य और संबंधों पर राहु के अशुभ प्रभावों को कम करता है।',
        items_included: ['Experienced Vedic Pandit', 'Rahu Yantra Energization', 'Havan Samagri', 'Prasad Distribution'],
        benefits: ['Career growth', 'Mental peace', 'Protection from negativity', 'Rahu dosh remedy']
    },
    {
        name: 'Ketu Vedic Mantra Jaap',
        name_hi: 'केतु वैदिक मन्त्र जाप',
        category: 'Mantra Jaap',
        base_price: 5100,
        duration: '2-3 Hours',
        mantra_count: '17,000',
        pandits_required: 1,
        description: 'Sacred Vedic mantra jaap for Ketu shanti, bringing spiritual growth and removal of obstacles.',
        description_hi: 'केतु ग्रह की शांति के लिए वैदिक मन्त्र जाप। आध्यात्मिक विकास और बाधाओं के निवारण हेतु।',
        items_included: ['Experienced Vedic Pandit', 'Ketu Yantra Energization', 'Havan Samagri', 'Prasad Distribution'],
        benefits: ['Spiritual growth', 'Obstacle removal', 'Moksha blessings', 'Ketu dosh remedy']
    },
    {
        name: 'Maha Mrityunjaya Mantra Jaap',
        name_hi: 'महामृत्युंजय मन्त्र जाप',
        category: 'Mantra Jaap',
        base_price: 11000,
        duration: '3 Days',
        mantra_count: '1,25,000',
        pandits_required: 2,
        description: 'The most powerful life-saving mantra jaap of Lord Shiva for health, longevity, and protection from untimely death.',
        description_hi: 'भगवान शिव का सबसे शक्तिशाली मंत्र जाप — स्वास्थ्य, दीर्घायु और अकाल मृत्यु से रक्षा हेतु।',
        items_included: ['2 Experienced Vedic Pandits', 'Rudraksha Mala', 'Bilva Patra', 'Havan with Ghee', 'Prasad & Bhandara'],
        benefits: ['Health & longevity', 'Protection from diseases', 'Victory over fear', 'Divine blessings of Shiva']
    },
    {
        name: 'Katyayani Mantra Jaap',
        name_hi: 'कात्यायनी जाप',
        category: 'Mantra Jaap',
        base_price: 7500,
        duration: '1-2 Days',
        mantra_count: '41,000',
        pandits_required: 1,
        description: 'Sacred jaap of Goddess Katyayani for marriage obstacles removal, relationship harmony, and fulfilling matrimonial wishes.',
        description_hi: 'माँ कात्यायनी का पवित्र जाप — विवाह में आ रही बाधाओं के निवारण और शुभ वैवाहिक जीवन हेतु।',
        items_included: ['Experienced Vedic Pandit', 'Katyayani Yantra', 'Red Flowers & Chunri', 'Havan Samagri'],
        benefits: ['Marriage obstacle removal', 'Relationship harmony', 'Marital bliss', 'Manglik dosh remedy']
    },
    // PATH & STOTRA
    {
        name: 'Durga Saptashati Paath (Samput)',
        name_hi: 'दुर्गा सप्तसती पाठ सम्पूट',
        category: 'Path & Stotra',
        base_price: 5500,
        duration: '4-5 Hours',
        pandits_required: 1,
        description: 'Complete recitation of Durga Saptashati with specific samput mantras for intensified divine protection and wish fulfillment.',
        description_hi: 'विशेष सम्पूट मन्त्रों के साथ दुर्गा सप्तसती का सम्पूर्ण पाठ — दिव्य सुरक्षा और मनोकामना पूर्ति हेतु।',
        items_included: ['Vedic Pandit', 'Durga Saptashati Book', 'Havan Samagri', 'Red Flowers & Chunri'],
        benefits: ['Divine protection', 'Wish fulfillment', 'Enemy protection', 'Goddess Durga blessings']
    },
    {
        name: 'Durga Saptashati Paath (Complete)',
        name_hi: 'दुर्गा सप्तसती पाठ सम्पूर्ण',
        category: 'Path & Stotra',
        base_price: 3100,
        duration: '3-4 Hours',
        pandits_required: 1,
        description: 'Full recitation of all 700 shlokas of Durga Saptashati for supreme blessings of Goddess Durga.',
        description_hi: 'माँ दुर्गा की कृपा प्राप्ति हेतु दुर्गा सप्तसती के सम्पूर्ण 700 श्लोकों का पाठ।',
        items_included: ['Vedic Pandit', 'Durga Saptashati Book', 'Incense & Flowers', 'Prasad'],
        benefits: ['Courage & strength', 'Negativity removal', 'Success in endeavors', 'Family protection']
    },
    // SANSKAR
    {
        name: 'Yagyopavit Sanskar (Janeu)',
        name_hi: 'यज्ञोपवित संस्कार (जनेऊ)',
        category: 'Sanskar',
        base_price: 5100,
        duration: '3-4 Hours',
        pandits_required: 1,
        description: 'Sacred thread ceremony marking the spiritual initiation of a boy into Vedic learning and responsibilities.',
        description_hi: 'बालक के वैदिक शिक्षा और कर्तव्यों में दीक्षा का पवित्र उपनयन संस्कार।',
        items_included: ['Experienced Vedic Pandit', 'Sacred Thread (Janeu)', 'Havan Samagri', 'Ganesh & Kalash Sthapana'],
        benefits: ['Spiritual initiation', 'Vedic education blessing', 'Character development', 'Family tradition']
    },
    {
        name: 'Karn Vedh Sanskar',
        name_hi: 'कर्ण वेध संस्कार',
        category: 'Sanskar',
        base_price: 2100,
        duration: '1-2 Hours',
        pandits_required: 1,
        description: 'Traditional ear-piercing ceremony performed with Vedic mantras for the well-being and longevity of the child.',
        description_hi: 'बालक/बालिका की दीर्घायु और कल्याण हेतु वैदिक मन्त्रों के साथ कर्ण छेदन संस्कार।',
        items_included: ['Vedic Pandit', 'Gold/Silver Needle', 'Havan Samagri', 'Prasad'],
        benefits: ['Child well-being', 'Longevity', 'Traditional blessing', 'Health benefits']
    },
    {
        name: 'Mundan Sanskar Puja',
        name_hi: 'मुंडन संस्कार पूजा',
        category: 'Sanskar',
        base_price: 3100,
        duration: '2-3 Hours',
        pandits_required: 1,
        description: 'First head-shaving ceremony of a child with full Vedic rituals for purification and good fortune.',
        description_hi: 'बालक के प्रथम मुंडन का पवित्र संस्कार — शुद्धि और शुभ भाग्य हेतु वैदिक विधि-विधान के साथ।',
        items_included: ['Vedic Pandit', 'Havan Samagri', 'Ganesh Puja', 'Navagraha Puja', 'Prasad & Bhandara'],
        benefits: ['Purification', 'Good fortune', 'Healthy hair growth', 'Positive energy']
    },
    // HOME & BUSINESS
    {
        name: 'Griha Pravesh Puja',
        name_hi: 'गृह प्रवेश पूजा',
        category: 'Home & Business',
        base_price: 5100,
        duration: '3-4 Hours',
        pandits_required: 2,
        description: 'Essential rituals for entering a new house with divine blessings for prosperity, peace, and protection.',
        description_hi: 'नए घर में प्रवेश के लिए आवश्यक पूजा — समृद्धि, शांति और सुरक्षा हेतु दिव्य आशीर्वाद।',
        items_included: ['2 Experienced Pandits', 'Ganesh & Kalash Sthapana', 'Vastu Puja', 'Navagraha Puja', 'Havan with Ghee', 'Prasad'],
        benefits: ['Prosperity', 'Peace & harmony', 'Vastu dosh removal', 'Divine protection']
    },
    {
        name: 'Bhumi Pujan',
        name_hi: 'भूमि पूजन',
        category: 'Home & Business',
        base_price: 5100,
        duration: '2-3 Hours',
        pandits_required: 1,
        description: 'Ground-breaking ceremony with Vedic rituals before construction to seek divine blessings for the land.',
        description_hi: 'निर्माण कार्य प्रारंभ से पूर्व भूमि पूजन — भूमि पर दिव्य आशीर्वाद प्राप्ति हेतु।',
        items_included: ['Vedic Pandit', 'Bhumi Puja Samagri', 'Nariyal & Kalash', 'Havan Samagri'],
        benefits: ['Auspicious beginning', 'Vastu harmony', 'Obstacle-free construction', 'Prosperity']
    },
    // DAAN
    {
        name: 'Grahan Daan',
        name_hi: 'ग्रहण दान',
        category: 'Daan & Charity',
        base_price: 2100,
        duration: '1 Hour',
        pandits_required: 1,
        description: 'Sacred charity during solar or lunar eclipse to neutralize negative effects and gain spiritual merit.',
        description_hi: 'सूर्य या चंद्र ग्रहण के समय नकारात्मक प्रभावों को दूर करने और पुण्य लाभ हेतु पवित्र दान।',
        samagri_available: false,
        items_included: ['Vedic Pandit', 'Daan Items (as per requirement)', 'Mantra Chanting'],
        benefits: ['Negative effect removal', 'Spiritual merit', 'Planetary pacification', 'Good karma']
    },
    // GRAHA PUJA
    {
        name: 'Shani Puja',
        name_hi: 'शनि पूजा',
        category: 'Graha Puja',
        base_price: 3100,
        duration: '2-3 Hours',
        pandits_required: 1,
        description: 'Dedicated puja to Lord Shani for relief from Sade Sati, Shani Dhaiya, and other Saturn-related afflictions.',
        description_hi: 'शनि देव की पूजा — साढ़ेसाती, शनि ढैय्या और शनि संबंधित कष्टों से राहत हेतु।',
        items_included: ['Vedic Pandit', 'Shani Yantra', 'Black Sesame & Mustard Oil', 'Iron Items', 'Havan Samagri'],
        benefits: ['Sade Sati relief', 'Career stability', 'Justice & discipline', 'Saturn blessings']
    },
    {
        name: 'Shukra Puja / Santoshi Mata / Vaibhav Lakshmi',
        name_hi: 'शुक्र पूजा, संतोषी माता, वैभव लक्ष्मी पूजा',
        category: 'Graha Puja',
        base_price: 3100,
        duration: '2-3 Hours',
        pandits_required: 1,
        description: 'Combined Venus puja with Santoshi Mata and Vaibhav Lakshmi worship for wealth, happiness, and marital harmony.',
        description_hi: 'धन, सुख और वैवाहिक सामंजस्य हेतु शुक्र पूजा, संतोषी माता और वैभव लक्ष्मी पूजा।',
        items_included: ['Vedic Pandit', 'White Flowers & Sweets', 'Lakshmi Yantra', 'Havan Samagri'],
        benefits: ['Wealth & prosperity', 'Marital harmony', 'Happiness', 'Venus blessings']
    },
    {
        name: 'Guru Puja / Brihaspati Puja',
        name_hi: 'गुरु पूजा, गुरु पूर्णिमा, बृहस्पति पूजा',
        category: 'Graha Puja',
        base_price: 3100,
        duration: '2-3 Hours',
        pandits_required: 1,
        description: 'Jupiter worship for wisdom, education, financial growth, and spiritual advancement.',
        description_hi: 'ज्ञान, शिक्षा, आर्थिक विकास और आध्यात्मिक उन्नति हेतु गुरु/बृहस्पति पूजा।',
        items_included: ['Vedic Pandit', 'Yellow Flowers & Turmeric', 'Guru Yantra', 'Havan Samagri'],
        benefits: ['Wisdom & knowledge', 'Educational success', 'Financial growth', 'Jupiter blessings']
    },
    {
        name: 'Budh Puja',
        name_hi: 'बुध पूजा',
        category: 'Graha Puja',
        base_price: 2500,
        duration: '2 Hours',
        pandits_required: 1,
        description: 'Mercury worship for enhanced communication, intellect, business acumen, and analytical abilities.',
        description_hi: 'बुद्धि, वाणी, व्यापार कौशल और विश्लेषणात्मक क्षमता वृद्धि हेतु बुध ग्रह पूजा।',
        items_included: ['Vedic Pandit', 'Green Items & Moong Dal', 'Budh Yantra', 'Havan Samagri'],
        benefits: ['Sharp intellect', 'Business success', 'Communication skills', 'Mercury blessings']
    },
    {
        name: 'Hanuman Dhwaja Rohan Puja',
        name_hi: 'हनुमान ध्वजा रोपण पूजा',
        category: 'Special Puja',
        base_price: 3500,
        duration: '2-3 Hours',
        pandits_required: 1,
        description: 'Installation of Hanuman flag with full Vedic rituals for protection, courage, and removal of evil forces.',
        description_hi: 'हनुमान जी के ध्वज स्थापना पूजा — सुरक्षा, साहस और बुरी शक्तियों से रक्षा हेतु।',
        items_included: ['Vedic Pandit', 'Hanuman Dhwaja (Flag)', 'Sindoor & Oil', 'Havan Samagri', 'Prasad'],
        benefits: ['Protection from evil', 'Courage & strength', 'Home protection', 'Hanuman blessings']
    },
    {
        name: 'Chandra Puja',
        name_hi: 'चंद्र पूजा',
        category: 'Graha Puja',
        base_price: 2500,
        duration: '2 Hours',
        pandits_required: 1,
        description: 'Moon worship for emotional balance, mental peace, and prosperity. Especially beneficial for Chandra dosh.',
        description_hi: 'चंद्र ग्रह की पूजा — भावनात्मक संतुलन, मानसिक शांति और समृद्धि हेतु। चंद्र दोष में विशेष लाभकारी।',
        items_included: ['Vedic Pandit', 'White Flowers & Rice', 'Chandra Yantra', 'Havan Samagri'],
        benefits: ['Mental peace', 'Emotional balance', 'Prosperity', 'Moon blessings']
    },
    {
        name: 'Mangal Puja',
        name_hi: 'मंगल पूजा',
        category: 'Graha Puja',
        base_price: 2500,
        duration: '2 Hours',
        pandits_required: 1,
        description: 'Mars worship for courage, property matters, marital harmony, and Manglik dosh remedy.',
        description_hi: 'मंगल ग्रह की पूजा — साहस, संपत्ति संबंधी मामले, वैवाहिक सामंजस्य और मांगलिक दोष निवारण हेतु।',
        items_included: ['Vedic Pandit', 'Red Flowers & Masoor Dal', 'Mangal Yantra', 'Havan Samagri'],
        benefits: ['Courage & confidence', 'Property success', 'Manglik remedy', 'Mars blessings']
    },
    {
        name: 'Durga Saptashati Paath (Chhuta)',
        name_hi: 'दुर्गा सप्तसती पाठ (छूटा)',
        category: 'Path & Stotra',
        base_price: 1500,
        duration: '1-2 Hours',
        pandits_required: 1,
        description: 'Selected chapters of Durga Saptashati for quick divine intervention and protection.',
        description_hi: 'त्वरित दिव्य हस्तक्षेप और सुरक्षा हेतु दुर्गा सप्तसती के चुनिंदा अध्यायों का पाठ।',
        items_included: ['Vedic Pandit', 'Durga Saptashati Book', 'Incense & Flowers'],
        benefits: ['Quick protection', 'Negativity removal', 'Courage', 'Goddess blessings']
    },
    {
        name: 'Sundar Kand Paath',
        name_hi: 'सुंदर कांड पाठ',
        category: 'Path & Stotra',
        base_price: 2100,
        duration: '2-3 Hours',
        pandits_required: 1,
        description: 'Recitation of Sundar Kand from Ramcharitmanas for removing obstacles and bringing good fortune.',
        description_hi: 'रामचरितमानस के सुंदर कांड का पाठ — बाधाओं के निवारण और शुभ भाग्य हेतु।',
        items_included: ['Vedic Pandit', 'Ramcharitmanas', 'Flowers & Incense', 'Prasad'],
        samagri_available: false,
        benefits: ['Obstacle removal', 'Good fortune', 'Hanuman blessings', 'Family harmony']
    },
    {
        name: 'Chalisa Paath',
        name_hi: 'चालीसा पाठ',
        category: 'Path & Stotra',
        base_price: 1100,
        duration: '1 Hour',
        pandits_required: 1,
        description: 'Recitation of sacred Chalisa (Hanuman/Durga/Shiv) for specific divine blessings and protection.',
        description_hi: 'विशेष दिव्य आशीर्वाद और सुरक्षा हेतु पवित्र चालीसा (हनुमान/दुर्गा/शिव) का पाठ।',
        items_included: ['Vedic Pandit', 'Chalisa Book', 'Flowers & Incense'],
        samagri_available: false,
        benefits: ['Divine protection', 'Wish fulfillment', 'Spiritual upliftment', 'Peace of mind']
    },
    {
        name: 'Vishnu Sahasranaam',
        name_hi: 'विष्णु सहस्रनाम',
        category: 'Path & Stotra',
        base_price: 2100,
        duration: '2 Hours',
        pandits_required: 1,
        description: 'Recitation of 1000 names of Lord Vishnu for prosperity, protection, and liberation.',
        description_hi: 'भगवान विष्णु के 1000 नामों का पाठ — समृद्धि, सुरक्षा और मोक्ष प्राप्ति हेतु।',
        items_included: ['Vedic Pandit', 'Vishnu Sahasranaam Book', 'Tulsi Leaves & Flowers'],
        samagri_available: false,
        benefits: ['Prosperity', 'Divine protection', 'Moksha path', 'Vishnu blessings']
    },
    {
        name: 'Business Inauguration Puja',
        name_hi: 'बिजनेस उद्घाटन पूजा',
        category: 'Home & Business',
        base_price: 5100,
        duration: '2-3 Hours',
        pandits_required: 1,
        description: 'Auspicious puja for new business/shop/office inauguration with Ganesh Puja, Lakshmi Puja, and Havan.',
        description_hi: 'नए व्यवसाय/दुकान/कार्यालय के शुभ उद्घाटन हेतु गणेश पूजा, लक्ष्मी पूजा और हवन।',
        items_included: ['Vedic Pandit', 'Ganesh & Lakshmi Murti', 'Kalash Sthapana', 'Havan Samagri', 'Nariyal & Flowers'],
        benefits: ['Business prosperity', 'Customer attraction', 'Obstacle removal', 'Financial growth']
    }
];
